import { ZoneListResponse } from '../interfaces/zone-list-response.interface';

/* eslint-disable @typescript-eslint/naming-convention */

export const ZONE_LIST_MOCK = () => [
  {
    ID: -1,
    Name: 'Root',
    Description: '',
    Units: null,
    MaxSeverity: 0,
    MaxUnAckSeverity: 1,
    Position: {
      Left: 0,
      Top: 0,
      Width: 0,
      Height: 0,
    },
  },
  {
    ID: 19,
    Name: 'Офис',
    Description: 'Дмитровская',
    Units: null,
    MaxSeverity: 0,
    MaxUnAckSeverity: 0,
    Position: {
      Left: 0,
      Top: 0,
      Width: 0,
      Height: 0,
    },
  },
  {
    ID: 20,
    Name: 'Зона 32',
    Description: 'Зона для Quasar 32',
    Units: [
      {
        Index: 24,
        Online: false,
        Info: {
          Address: '172.17.42.183:39842',
          Name: 'Quasar-32x_183',
          Description: 'QUASAR-183',
          Device: {
            HWPlatform: '',
            SWVersion: '',
            Serial: 'AJ43012937',
            MacAddr: '',
          },
          Timestamp: '2022-05-30T10:29:03.197322Z',
        },
        State: {
          CpuUsage: 0,
          Rx: {
            Bytes: 0,
            Packets: 0,
            BitRate: 0,
            PktRate: 0,
            DroppedPkts: 0,
          },
          Tx: {
            Bytes: 0,
            Packets: 0,
            BitRate: 0,
            PktRate: 0,
            DroppedPkts: 0,
          },
        },
        MaxSeverity: 3,
        MaxUnAckSeverity: 1,
        Position: {
          Left: 0,
          Top: 0,
          Width: 0,
          Height: 0,
        },
      },
      {
        Index: 33,
        Online: false,
        Info: {
          Address: '172.17.41.176:46304',
          Name: 'Quasar-32x_176',
          Description: 'QUASAR-176',
          Device: {
            HWPlatform: '',
            SWVersion: '',
            Serial: 'FDJNB28003D',
            MacAddr: '',
          },
          Timestamp: '2022-07-13T14:31:30.462898Z',
        },
        State: {
          CpuUsage: 0,
          Rx: {
            Bytes: 0,
            Packets: 0,
            BitRate: 0,
            PktRate: 0,
            DroppedPkts: 0,
          },
          Tx: {
            Bytes: 0,
            Packets: 0,
            BitRate: 0,
            PktRate: 0,
            DroppedPkts: 0,
          },
        },
        MaxSeverity: 3,
        MaxUnAckSeverity: 1,
        Position: {
          Left: 0,
          Top: 0,
          Width: 0,
          Height: 0,
        },
      },
    ],
    MaxSeverity: 0,
    MaxUnAckSeverity: 0,
    Position: {
      Left: 0,
      Top: 0,
      Width: 0,
      Height: 0,
    },
  },
  {
    ID: 21,
    Name: 'Зона 64',
    Description: 'Зона для Quasar 64',
    Units: [
      {
        Index: 32,
        Online: true,
        Info: {
          Address: '172.17.41.175:57948',
          Name: 'Quasar-64x_175',
          Description: 'QUASAR-175',
          Device: {
            HWPlatform: '',
            SWVersion: '',
            Serial: 'WFSNB230005B1',
            MacAddr: '',
          },
          Timestamp: '2022-07-13T14:01:22.217114Z',
        },
        State: {
          CpuUsage: 0,
          Rx: {
            Bytes: 0,
            Packets: 0,
            BitRate: 0,
            PktRate: 0,
            DroppedPkts: 0,
          },
          Tx: {
            Bytes: 0,
            Packets: 0,
            BitRate: 0,
            PktRate: 0,
            DroppedPkts: 0,
          },
        },
        MaxSeverity: 3,
        MaxUnAckSeverity: 1,
        Position: {
          Left: 0,
          Top: 0,
          Width: 0,
          Height: 0,
        },
      },
    ],
    MaxSeverity: 0,
    MaxUnAckSeverity: 0,
    Position: {
      Left: 0,
      Top: 0,
      Width: 0,
      Height: 0,
    },
  },
  {
    ID: 23,
    Name: 'TEST',
    Description: 'Тестовая зона',
    Units: [
      {
        Index: 34,
        Online: false,
        Info: {
          Address: '172.17.42.177:56308',
          Name: 'Quasar-32x_177',
          Description: 'QUASAR-177',
          Device: {
            HWPlatform: '',
            SWVersion: '',
            Serial: 'FDJNA360003',
            MacAddr: '',
          },
          Timestamp: '2022-07-13T17:10:43.898386Z',
        },
        State: {
          CpuUsage: 0,
          Rx: {
            Bytes: 0,
            Packets: 0,
            BitRate: 0,
            PktRate: 0,
            DroppedPkts: 0,
          },
          Tx: {
            Bytes: 0,
            Packets: 0,
            BitRate: 0,
            PktRate: 0,
            DroppedPkts: 0,
          },
        },
        MaxSeverity: 3,
        MaxUnAckSeverity: 1,
        Position: {
          Left: 0,
          Top: 0,
          Width: 0,
          Height: 0,
        },
      },
    ],
    MaxSeverity: 0,
    MaxUnAckSeverity: 0,
    Position: {
      Left: 0,
      Top: 0,
      Width: 0,
      Height: 0,
    },
  },
  {
    ID: 26,
    Name: 'test2',
    Description: 'Jigurda',
    Units: null,
    MaxSeverity: 0,
    MaxUnAckSeverity: 0,
    Position: {
      Left: 0,
      Top: 0,
      Width: 0,
      Height: 0,
    },
  },
  {
    ID: 28,
    Name: 'Zone 123',
    Description: '',
    Units: null,
    MaxSeverity: 0,
    MaxUnAckSeverity: 0,
    Position: {
      Left: 0,
      Top: 0,
      Width: 0,
      Height: 0,
    },
  },
] as ZoneListResponse[];
